-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 16:45:20 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`AccessLevels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AccessLevels` (
  `idAccess` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccess`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Apellido1` VARCHAR(45) NULL,
  `Apellido2` VARCHAR(45) NULL,
  `Nombre1` VARCHAR(45) NULL,
  `Nombre2` VARCHAR(45) NULL,
  `LoginName` VARCHAR(45) NULL,
  `Password` VARCHAR(500) NULL,
  `idAccess` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Access_Lavel_idx` (`idAccess` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Access_Lavel`
    FOREIGN KEY (`idAccess`)
    REFERENCES `mydb`.`AccessLevels` (`idAccess`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Misiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Misiones` (
  `idMision` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha` DATE NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idMision`),
  INDEX `fk_Mision_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Mision_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sensores` (
  `idSensor` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idSensor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mediciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mediciones` (
  `idMedicion` INT NOT NULL AUTO_INCREMENT,
  `FechayHora` DATETIME NULL,
  `idMision` INT NOT NULL,
  `idSensor` INT NOT NULL,
  `Valor` REAL NULL,
  PRIMARY KEY (`idMedicion`),
  INDEX `fk_Mediciones_Mision1_idx` (`idMision` ASC) VISIBLE,
  INDEX `fk_Mediciones_Sensor1_idx` (`idSensor` ASC) VISIBLE,
  CONSTRAINT `fk_Mediciones_Mision1`
    FOREIGN KEY (`idMision`)
    REFERENCES `mydb`.`Misiones` (`idMision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mediciones_Sensor1`
    FOREIGN KEY (`idSensor`)
    REFERENCES `mydb`.`Sensores` (`idSensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
